<a href="https://colab.research.google.com/github/amandarice97/data-analytics/blob/main/Classwork_Homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Classwork #1, Question #1**

In [ ]:
(2**5)/(7*(4-2**3))

-1.1428571428571428

**Classwork #1, Question #2**

20 == '20'

x = 4.0
y = .5

x < y or 3*y < x

In [ ]:
20=="20"

False

In [ ]:
x = 4.0
y = .5
x < y or 3*y < x

True

**Classwork #1, Question #3**

fare = "$10.00"
tip = "2.00$"
tax = "$ 0.80"

Write a Python code that uses slicing and the print() function to print out the following message:

The total trip cost is: $12.80

In [ ]:
fare = float ("10.00")
fare

10.0

In [ ]:
fare = "$10.00"
fare = fare [1:]
fare = float (fare)
fare

10.0

In [ ]:
tip = "2.00$"
tip = tip [-5:-2]
tip = float (tip)
tip

2.0

In [ ]:
tax = "$0.80"
tax = float (tax [2:])
tax

0.8

In [ ]:
total = fare + tip + tax
total

12.8

In [ ]:
print("The total trip cost is $", total)

The total trip cost is $ 12.8

**Classwork #1, Question #4**

list_variable = [100, 144, 169, 1000, 8]

Write a Python code that uses print() and max() functions to print out the largest value in the list, list_variable, as follows:

The largest value in the list is: 1000

In [18]:
list_variable = [100, 144, 169, 1000, 8]
max(list_variable)

1000

In [19]:
print("The largest value in the list is:", max(list_variable))

The largest value in the list is: 1000

**Classwork #1, Question #5**

Import the pandas library as pd

In [20]:
import pandas

In [22]:
beer = pandas.read_csv("http://bcdanl.github.io/data/beer_markets.csv")
beer

,hh,_purchase_desc,quantity,brand,dollar_spent,beer_floz,price_per_floz,container,promo,market,...,age,employment,degree,cow,race,microwave,dishwasher,tvcable,singlefamilyhome,npeople
0,2000946,BUD LT BR CN 12P,1,BUD LIGHT,8.14,144.0,0.056528,CAN,False,RURAL ILLINOIS,...,50+,none,Grad,none/retired/student,white,True,True,premium,False,1
1,2003036,BUD LT BR CN 24P,1,BUD LIGHT,17.48,288.0,0.060694,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
2,2003036,BUD LT BR CN 24P,2,BUD LIGHT,33.92,576.0,0.058889,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
3,2003036,BUD LT BR CN 30P,2,BUD LIGHT,34.74,720.0,0.048250,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
4,2003036,BUD LT BR CN 36P,2,BUD LIGHT,40.48,864.0,0.046852,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73110,9158319,NATURAL LT BR CN 24P,1,NATURAL LIGHT,11.49,288.0,0.039896,CAN,True,RURAL VIRGINIA,...,50+,none,HS,none/retired/student,black,True,True,premium,True,2
73111,9158319,NATURAL LT BR CN 24P,1,NATURAL LIGHT,9.97,288.0,0.034618,CAN,False,RURAL VIRGINIA,...,50+,none,HS,none/retired/student,black,True,True,premium,True,2
73112,9158319,NATURAL LT BR CN 24P,1,NATURAL LIGHT,9.98,288.0,0.034653,CAN,False,RURAL VIRGINIA,...,50+,none,HS,none/retired/student,black,True,True,premium,True,2
73113,9164033,NATURAL LT BR CN 30P,1,NATURAL LIGHT,12.98,360.0,0.036056,CAN,False,SACRAMENTO,...,50+,full,College,prof,hispanic,True,True,basic,True,5plus
73114,9164155,NATURAL LT BR CN 24P,1,NATURAL LIGHT,13.49,288.0,0.046840,CAN,False,JACKSONVILLE,...,50+,full,HS,labor/craft/military/farm,white,True,True,none,True,2

In [23]:
type(beer)

pandas.core.frame.DataFrame

In [24]:
import pandas as pd

In [25]:
beer = pd.read_csv("http://bcdanl.github.io/data/beer_markets.csv")
beer

,hh,_purchase_desc,quantity,brand,dollar_spent,beer_floz,price_per_floz,container,promo,market,...,age,employment,degree,cow,race,microwave,dishwasher,tvcable,singlefamilyhome,npeople
0,2000946,BUD LT BR CN 12P,1,BUD LIGHT,8.14,144.0,0.056528,CAN,False,RURAL ILLINOIS,...,50+,none,Grad,none/retired/student,white,True,True,premium,False,1
1,2003036,BUD LT BR CN 24P,1,BUD LIGHT,17.48,288.0,0.060694,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
2,2003036,BUD LT BR CN 24P,2,BUD LIGHT,33.92,576.0,0.058889,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
3,2003036,BUD LT BR CN 30P,2,BUD LIGHT,34.74,720.0,0.048250,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
4,2003036,BUD LT BR CN 36P,2,BUD LIGHT,40.48,864.0,0.046852,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73110,9158319,NATURAL LT BR CN 24P,1,NATURAL LIGHT,11.49,288.0,0.039896,CAN,True,RURAL VIRGINIA,...,50+,none,HS,none/retired/student,black,True,True,premium,True,2
73111,9158319,NATURAL LT BR CN 24P,1,NATURAL LIGHT,9.97,288.0,0.034618,CAN,False,RURAL VIRGINIA,...,50+,none,HS,none/retired/student,black,True,True,premium,True,2
73112,9158319,NATURAL LT BR CN 24P,1,NATURAL LIGHT,9.98,288.0,0.034653,CAN,False,RURAL VIRGINIA,...,50+,none,HS,none/retired/student,black,True,True,premium,True,2
73113,9164033,NATURAL LT BR CN 30P,1,NATURAL LIGHT,12.98,360.0,0.036056,CAN,False,SACRAMENTO,...,50+,full,College,prof,hispanic,True,True,basic,True,5plus
73114,9164155,NATURAL LT BR CN 24P,1,NATURAL LIGHT,13.49,288.0,0.046840,CAN,False,JACKSONVILLE,...,50+,full,HS,labor/craft/military/farm,white,True,True,none,True,2