<a href="https://colab.research.google.com/github/amandarice97/data-analytics/blob/main/danl-m1-hw6-Rice-Amanda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 6
Load the DataFrame for Part 1.

*Answer*

In [ ]:
import pandas as pd
climate_finance = pd.read_csv('https://bcdanl.github.io/data/climate_finance.csv',
                              parse_dates = ["Year"])
climate_finance

,Party,Recipient country/region,Project/programme/activity,Type of support,Year,Currency,Contribution,Status,Funding source,Financial instrument,Sector,Energy
0,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,11074.20,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
1,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,12275.56,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
2,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,22148.39,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
3,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,22148.39,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
4,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,22148.39,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
...,...,...,...,...,...,...,...,...,...,...,...,...
16848,United States of America,Global,Solar Energy Transformation Fund LLC (Senior),mitigation,2018-01-01,USD,22500000.00,committed,Oof,Non-concessional Loan,Energy,True
16849,United States of America,Ukraine,Zaporizhia Wind Farm,mitigation,2018-01-01,USD,22500000.00,committed,Other,Other,Energy,True
16850,United States of America,Ukraine,Zaporizhia Wind Farm,mitigation,2018-01-01,USD,22500000.00,committed,Other,Other,Energy,True
16851,United States of America,Africa,Power Africa Indefinite Delivery/Indefinite Qu...,mitigation,2018-01-01,USD,34940000.00,committed,Oda,Grant,Energy,True
16852,United States of America,Kenya,Kipeto Wind Farm,mitigation,2018-01-01,USD,50000000.00,committed,Other,Other,Energy,True

Climate finance refers to local, national or transnational financing—drawn from public, private and alternative sources of financing—that seeks to support mitigation and adaptation actions that will address climate change (https://unfccc.int/topics/introduction-to-climate-finance).

Mitigation involves taking actions to reduce the emissions of greenhouse gases that are responsible for climate change.

Adaptation involves taking actions to reduce the actual or expected damages from climate change (https://climate.nasa.gov/solutions/adaptation-mitigation).

A unit of observation in climate_finance DataFrame is a climate change project.

# Variable Description
- Party: a party (country) that provides a funding contribution to recipient country/region for their cliamte change project.
- Recipient country/region: Recipient country or region
- Project/programme/activity: Details in the climate change project
- Type of support:
  - adaptation if the climate change project is related to adaptation project.
  - mitigation if the climate change project is related to mitigation project.
- Year: Year that funding contribution is committed or provided.
- Contribution: An amount of funding contribution for the climate change project (in USD).
- Status:
  - committed if a party commits to providing the funding contribution for the climate change project, but the funding contribution is NOT actually provided.
  - provided if the funding contribution was provided for the climate change project.
- Energy:
  - TRUE if the project is energy-related;
  - FALSE otherwise.

# Question 1
For each party, calculate the total funding contributions that were disbursed or provided for mitigation projects for each year.

*Answer*

In [ ]:
climate_finance.info() # column name, count, data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16853 entries, 0 to 16852
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Party                       16853 non-null  object
 1   Recipient country/region    16853 non-null  object
 2   Project/programme/activity  16853 non-null  object
 3   Type of support             16853 non-null  object
 4   Year                        16853 non-null  datetime64[ns]
 5   Currency                    16853 non-null  object
 6   Contribution                16853 non-null  float64
 7   Status                      16853 non-null  object
 8   Funding source              16853 non-null  object
 9   Financial instrument        16850 non-null  object
 10  Sector                      16794 non-null  object
 11  Energy                      16794 non-null  object
dtypes: datetime64[ns](1), float64(1), object(10)
memory usage: 1.5+ MB

In [ ]:
climate_finance.nunique() # unique values by variable

Party                            34
Recipient country/region       1310
Project/programme/activity     8590
Type of support                   2
Year                              8
Currency                          1
Contribution                  11688
Status                            3
Funding source                   55
Financial instrument            106
Sector                          968
Energy                            2
dtype: int64

In [ ]:
provided = climate_finance["Status"] == "provided"
mitigation = climate_finance["Type of support"] == "mitigation"
climate_finance[ provided & mitigation] # filter by Status = provided, Type of support = mitigation

,Party,Recipient country/region,Project/programme/activity,Type of support,Year,Currency,Contribution,Status,Funding source,Financial instrument,Sector,Energy
20,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,77249169.44,provided,20 OOF,900 Other,Other (430 Cross-cutting),False
66,Austria,612 Georgia,612 Georgia,mitigation,2015-01-01,USD,6090808.42,provided,10 ODA,520 CIV shares,Other (232 Energy),True
122,Austria,"289 South of Sahara, regional",289 South of Sahara|regional,mitigation,2015-01-01,USD,8084163.90,provided,10 ODA,520 CIV shares,Other (232 Energy),True
195,Australia,Asia Pacific,Asia Pacific,mitigation,2013-01-01,USD,26000.00,provided,ODA,Grant,Industry,False
206,Australia,South Asia,South Asia,mitigation,2013-01-01,USD,265000.00,provided,ODA,Grant,Cross-cutting,False
...,...,...,...,...,...,...,...,...,...,...,...,...
13604,Switzerland,Far East,SECO Climate Change Mitigation,mitigation,2014-01-01,USD,5737683.00,provided,ODA,Grant,Cross-cutting,False
13605,Switzerland,Eastern Europe,SECO Climate Change Mitigation,mitigation,2014-01-01,USD,5813122.00,provided,ODA,Grant,Cross-cutting,False
13606,Switzerland,North Africa,SECO Climate Change Mitigation,mitigation,2014-01-01,USD,6107308.00,provided,ODA,Grant,Cross-cutting,False
13608,Switzerland,Global,SDC Global Mitigation Programs and Projects,mitigation,2014-01-01,USD,7654812.00,provided,ODA,Grant,Cross-cutting,False
13611,Switzerland,Global,SECO Climate Change Mitigation,mitigation,2014-01-01,USD,12254404.00,provided,ODA,Grant,Cross-cutting,False

In [ ]:
party_and_year = climate_finance.groupby(["Party", "Year"]) # group by Party then Year

In [ ]:
party_and_year["Contribution"].sum() # sum of contributions by Party per Year

Party                     Year
Australia                 2013-01-01    8.288000e+06
                          2014-01-01    9.846000e+06
Austria                   2015-01-01    1.909721e+08
                          2016-01-01    1.829671e+08
                          2017-01-01    1.358941e+08
                                            ...
United States of America  2014-01-01    1.055342e+09
                          2015-01-01    1.211856e+09
                          2016-01-01    9.272847e+08
                          2017-01-01    9.208300e+08
                          2018-01-01    5.548530e+08
Name: Contribution, Length: 176, dtype: float64

# Question 2
How many parties have provided positive funding contributions to other countries or regions for their adaptation projects for every single year from 2011 to 2018?

*Answer*

In [ ]:
climate_finance

,level_0,index,Party,Recipient country/region,Project/programme/activity,Type of support,Year,Currency,Contribution,Status,Funding source,Financial instrument,Sector,Energy
0,0,0,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,11074.20,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
1,1,1,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,12275.56,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
2,2,2,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,22148.39,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
3,3,3,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,22148.39,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
4,4,4,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,22148.39,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16848,16848,16848,United States of America,Global,Solar Energy Transformation Fund LLC (Senior),mitigation,2018-01-01,USD,22500000.00,committed,Oof,Non-concessional Loan,Energy,True
16849,16849,16849,United States of America,Ukraine,Zaporizhia Wind Farm,mitigation,2018-01-01,USD,22500000.00,committed,Other,Other,Energy,True
16850,16850,16850,United States of America,Ukraine,Zaporizhia Wind Farm,mitigation,2018-01-01,USD,22500000.00,committed,Other,Other,Energy,True
16851,16851,16851,United States of America,Africa,Power Africa Indefinite Delivery/Indefinite Qu...,mitigation,2018-01-01,USD,34940000.00,committed,Oda,Grant,Energy,True
16852,16852,16852,United States of America,Kenya,Kipeto Wind Farm,mitigation,2018-01-01,USD,50000000.00,committed,Other,Other,Energy,True

In [ ]:
greater_than_0 = climate_finance["Contribution"] > 0 # filter by positive contributions
climate_finance[ greater_than_0 ]

,level_0,index,Party,Recipient country/region,Project/programme/activity,Type of support,Year,Currency,Contribution,Status,Funding source,Financial instrument,Sector,Energy
0,0,0,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,11074.20,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
1,1,1,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,12275.56,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
2,2,2,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,22148.39,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
3,3,3,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,22148.39,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
4,4,4,Austria,"998 Developing countries, unspecified",998 Developing countries|unspecified,mitigation,2015-01-01,USD,22148.39,committed,10 ODA,110 Standard Grant,Other (410 Cross-cutting),False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16848,16848,16848,United States of America,Global,Solar Energy Transformation Fund LLC (Senior),mitigation,2018-01-01,USD,22500000.00,committed,Oof,Non-concessional Loan,Energy,True
16849,16849,16849,United States of America,Ukraine,Zaporizhia Wind Farm,mitigation,2018-01-01,USD,22500000.00,committed,Other,Other,Energy,True
16850,16850,16850,United States of America,Ukraine,Zaporizhia Wind Farm,mitigation,2018-01-01,USD,22500000.00,committed,Other,Other,Energy,True
16851,16851,16851,United States of America,Africa,Power Africa Indefinite Delivery/Indefinite Qu...,mitigation,2018-01-01,USD,34940000.00,committed,Oda,Grant,Energy,True
16852,16852,16852,United States of America,Kenya,Kipeto Wind Farm,mitigation,2018-01-01,USD,50000000.00,committed,Other,Other,Energy,True

In [ ]:
party_and_year = climate_finance.groupby(["Party", "Year"]) # group by Party then Year

In [ ]:
party_and_year["Contribution"].count() # count of contributions by Party per Year

Party                     Year
Australia                 2013-01-01     20
                          2014-01-01     11
Austria                   2015-01-01     86
                          2016-01-01    107
                          2017-01-01    103
                                       ...
United States of America  2014-01-01    118
                          2015-01-01    735
                          2016-01-01    646
                          2017-01-01    421
                          2018-01-01    371
Name: Contribution, Length: 176, dtype: int64

# Part 2
Consider the stock DataFrame for Part 2.

In [2]:
import pandas as pd
path = 'https://bcdanl.github.io/data/stock_2019_2024.csv' # import dataset
stock = pd.read_csv(path)
stock

,company,Date,Open,High,Low,Close,Adj Close,Volume
0,AMZN,2019-01-02,73.260002,77.667999,73.046501,76.956497,76.956497,159662000
1,APPL,2019-01-02,38.722500,39.712502,38.557499,39.480000,37.845036,148158800
2,GOOG,2019-01-02,50.828499,52.616001,50.785500,52.292500,52.292500,30652000
3,META,2019-01-02,128.990005,137.509995,128.559998,135.679993,135.536194,28146200
4,MSFT,2019-01-02,99.550003,101.750000,98.940002,101.120003,95.846024,35329300
...,...,...,...,...,...,...,...,...
9144,GOOG,2024-03-12,138.250000,140.279999,138.238998,139.619995,139.619995,18915904
9145,META,2024-03-12,493.260010,502.309998,484.790009,499.750000,499.750000,15339837
9146,MSFT,2024-03-12,407.619995,415.570007,406.790009,415.279999,415.279999,21388946
9147,NVDA,2024-03-12,880.489990,919.599976,861.729980,919.130005,919.130005,65246211
9148,TSLA,2024-03-12,177.770004,179.429993,172.410095,177.539993,177.539993,86753934

# Question 3
What are the minimum, first quartile, median, thrid quartile, maximum, mean, and standard deviation of Close and Volume for each company?

Hint: describe() is available for DataFrameGroupBy.

*Answer*

In [ ]:
stock.info() # column name, count, data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9149 entries, 0 to 9148
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   company    9149 non-null   object
 1   Date       9149 non-null   object
 2   Open       9149 non-null   float64
 3   High       9149 non-null   float64
 4   Low        9149 non-null   float64
 5   Close      9149 non-null   float64
 6   Adj Close  9149 non-null   float64
 7   Volume     9149 non-null   int64
dtypes: float64(5), int64(1), object(2)
memory usage: 571.9+ KB

In [ ]:
stock["company"].nunique() # unique values for company

7

In [ ]:
(
    stock
    .groupby("company")[['Close']] # group by company, descriptive statistics for Close
    .describe()
)

          Close                                                             \
          count        mean         std        min         25%         50%
company
AMZN     1307.0  129.022394   31.459520  75.014000   95.995750  129.119995
APPL     1307.0  125.317930   47.111511  35.547501   78.976250  136.910004
GOOG     1307.0  100.373253   30.762885  50.803001   70.798500  102.220001
META     1307.0  243.210161   78.512222  88.910004  182.485001  226.289993
MSFT     1307.0  242.420459   77.624389  97.400002  180.009995  246.270004
NVDA     1307.0  196.307827  157.005433  31.997499   72.831249  152.059998
TSLA     1307.0  172.018666  106.475295  11.931333   52.063999  199.679993


                75%         max
company
AMZN     159.001747  186.570496
APPL     164.415001  198.110001
GOOG     129.783745  154.839996
META     303.934998  512.190002
MSFT     299.815002  420.549988
NVDA     247.224998  926.690002
TSLA     250.215004  409.970001

In [ ]:
(
    stock
    .groupby("company")[['Volume']]
    .describe()
)

         Volume                                                      \
          count          mean           std         min         25%
company
AMZN     1307.0  7.467231e+07  3.345963e+07  17626000.0  52393250.0
APPL     1307.0  1.000267e+08  5.233516e+07  24048300.0  66187900.0
GOOG     1307.0  2.889379e+07  1.270505e+07   6936000.0  20826650.0
META     1307.0  2.328853e+07  1.542801e+07   5467500.0  14838100.0
MSFT     1307.0  2.919965e+07  1.223790e+07   8989200.0  21510350.0
NVDA     1307.0  4.652100e+07  1.989035e+07   9788400.0  32925400.0
TSLA     1307.0  1.329812e+08  8.410050e+07  29401800.0  81342300.0


                 50%          75%          max
company
AMZN      65266100.0   87283100.0  311346000.0
APPL      87360000.0  117386750.0  426510000.0
GOOG      25888000.0   32899000.0  124140000.0
META      19434200.0   27180750.0  232316600.0
MSFT      26292900.0   33162000.0   97012700.0
NVDA      43474400.0   56546800.0  251152800.0
TSLA     108834000.0  155254500.0  914082000.0

# Question 4
Find the 10 largest values for Volume for each company using a lambda function.

*Answer*

In [ ]:
company_1 = stock.groupby("company") # group by company
len(company_1)
company_1.size()

company
AMZN    1307
APPL    1307
GOOG    1307
META    1307
MSFT    1307
NVDA    1307
TSLA    1307
dtype: int64

In [ ]:
company_1.apply(lambda df: df.nlargest(10, "Volume", keep = "all")) # 10 largest values for Volume using lambda

             company        Date        Open        High         Low  \
company
AMZN    1904    AMZN  2020-01-31  102.573502  102.786003  100.113503
        5866    AMZN  2022-04-29  129.848999  130.761002  121.625000
        5460    AMZN  2022-02-04  155.606506  161.199997  150.608002
        2268    AMZN  2020-04-16  117.300003  123.050003  116.750000
        147     AMZN  2019-02-01   81.944000   83.653000   81.100502
...              ...         ...         ...         ...         ...
TSLA    2694    TSLA  2020-07-13  110.599998  119.666000   98.073997
        2351    TSLA  2020-05-01   50.333332   51.518002   45.535999
        1861    TSLA  2020-01-22   38.125999   39.633331   37.273335
        1798    TSLA  2020-01-08   31.580000   33.232666   31.215334
        2260    TSLA  2020-04-14   46.598000   49.458668   46.161999

                   Close   Adj Close     Volume
company
AMZN    1904  100.435997  100.435997  311346000
        5866  124.281502  124.281502  272662000
        5460  157.639496  157.639496  253456000
        2268  120.409500  120.409500  240764000
        147    81.311501   81.311501  230124000
...                  ...         ...        ...
TSLA    2694   99.804001   99.804001  584781000
        2351   46.754665   46.754665  487977000
        1861   37.970669   37.970669  470535000
        1798   32.809334   32.809334  467164500
        2260   47.326000   47.326000  458647500

[70 rows x 8 columns]

# Question 5
Calculate the Z-score of Close for each company on Date.
The formula for the Z-score of Close for each company on Date is as follows:

z(t) = [Close(t)-mean(Close(t))]/[std(Close(t))]

where

- Close(t) is a company’s Close price on date t;
- mean(Close(t)) is the mean value of Close for a company;
- std(Close(t))is the standard deviation of Close for a company.

*Answer*

In [ ]:
stock['Close_mean'] = stock['Close'].mean() # calculate mean
stock['Close_mean']

0       172.667242
1       172.667242
2       172.667242
3       172.667242
4       172.667242
           ...
9144    172.667242
9145    172.667242
9146    172.667242
9147    172.667242
9148    172.667242
Name: Close_mean, Length: 9149, dtype: float64

In [ ]:
stock['Close_std'] = stock['Close'].std() # calculate std. deviation
stock['Close_std']

0       101.471432
1       101.471432
2       101.471432
3       101.471432
4       101.471432
           ...
9144    101.471432
9145    101.471432
9146    101.471432
9147    101.471432
9148    101.471432
Name: Close_std, Length: 9149, dtype: float64

In [ ]:
stock['z_score'] = (stock['Close'] - stock['Close_mean'])/stock['Close_std'] # calculate z-score
stock['z_score']

0      -0.943228
1      -1.312559
2      -1.186292
3      -0.364509
4      -0.705097
          ...
9144   -0.325680
9145    3.223397
9146    2.390946
9147    7.356383
9148    0.048021
Name: z_score, Length: 9149, dtype: float64

# Question 6
Use the transform() method on the stock data to represent all the values of Open, High, Low, Close, Adj Close, and Volume in terms of the first date in the data.

To do so, divide all values for each company by the values of the first date in the data for that company.

*Answer*

In [ ]:
stock['all_values'] = stock['Open'] + stock['High'] + stock['Low'] + stock['Close'] + stock['Adj Close'] + stock['Volume'] # create new variable
stock

,company,Date,Open,High,Low,Close,Adj Close,Volume,all_values
0,AMZN,2019-01-02,73.260002,77.667999,73.046501,76.956497,76.956497,159662000,1.596624e+08
1,APPL,2019-01-02,38.722500,39.712502,38.557499,39.480000,37.845036,148158800,1.481590e+08
2,GOOG,2019-01-02,50.828499,52.616001,50.785500,52.292500,52.292500,30652000,3.065226e+07
3,META,2019-01-02,128.990005,137.509995,128.559998,135.679993,135.536194,28146200,2.814687e+07
4,MSFT,2019-01-02,99.550003,101.750000,98.940002,101.120003,95.846024,35329300,3.532980e+07
...,...,...,...,...,...,...,...,...,...
9144,GOOG,2024-03-12,138.250000,140.279999,138.238998,139.619995,139.619995,18915904,1.891660e+07
9145,META,2024-03-12,493.260010,502.309998,484.790009,499.750000,499.750000,15339837,1.534232e+07
9146,MSFT,2024-03-12,407.619995,415.570007,406.790009,415.279999,415.279999,21388946,2.139101e+07
9147,NVDA,2024-03-12,880.489990,919.599976,861.729980,919.130005,919.130005,65246211,6.525071e+07
9148,TSLA,2024-03-12,177.770004,179.429993,172.410095,177.539993,177.539993,86753934,8.675482e+07

In [ ]:
(
    stock
    .sort_values(["Date", "company"], # sort values by date, then company to identify first date
                 ascending=True)
)

,company,Date,Open,High,Low,Close,Adj Close,Volume,all_values
0,AMZN,2019-01-02,73.260002,77.667999,73.046501,76.956497,76.956497,159662000,1.596624e+08
1,APPL,2019-01-02,38.722500,39.712502,38.557499,39.480000,37.845036,148158800,1.481590e+08
2,GOOG,2019-01-02,50.828499,52.616001,50.785500,52.292500,52.292500,30652000,3.065226e+07
3,META,2019-01-02,128.990005,137.509995,128.559998,135.679993,135.536194,28146200,2.814687e+07
4,MSFT,2019-01-02,99.550003,101.750000,98.940002,101.120003,95.846024,35329300,3.532980e+07
...,...,...,...,...,...,...,...,...,...
9144,GOOG,2024-03-12,138.250000,140.279999,138.238998,139.619995,139.619995,18915904,1.891660e+07
9145,META,2024-03-12,493.260010,502.309998,484.790009,499.750000,499.750000,15339837,1.534232e+07
9146,MSFT,2024-03-12,407.619995,415.570007,406.790009,415.279999,415.279999,21388946,2.139101e+07
9147,NVDA,2024-03-12,880.489990,919.599976,861.729980,919.130005,919.130005,65246211,6.525071e+07
9148,TSLA,2024-03-12,177.770004,179.429993,172.410095,177.539993,177.539993,86753934,8.675482e+07

In [3]:
df = stock # I can't take credit for solving this, thank you Brian!

In [4]:
df['Date'] = pd.to_datetime(df['Date'])

In [5]:
df['first_date'] = df.groupby('company')['Date'].transform('min')

In [6]:
first_date_obs = df[df['Date'] == df['first_date']].drop('first_date', axis=1)

In [7]:
print(first_date_obs)

  company       Date        Open        High         Low       Close  \
0    AMZN 2019-01-02   73.260002   77.667999   73.046501   76.956497
1    APPL 2019-01-02   38.722500   39.712502   38.557499   39.480000
2    GOOG 2019-01-02   50.828499   52.616001   50.785500   52.292500
3    META 2019-01-02  128.990005  137.509995  128.559998  135.679993
4    MSFT 2019-01-02   99.550003  101.750000   98.940002  101.120003
5    NVDA 2019-01-02   32.660000   34.619999   32.512501   34.055000
6    TSLA 2019-01-02   20.406668   21.008667   19.920000   20.674667

    Adj Close     Volume
0   76.956497  159662000
1   37.845036  148158800
2   52.292500   30652000
3  135.536194   28146200
4   95.846024   35329300
5   33.788895   50875200
6   20.674667  174879000